spring:
  datasource:
    url: jdbc:mysql://192.168.137.1:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
server:
  port: 8099